steps:
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Retrieve Secrets from Secret Manager"
    args:
      - "secrets"
      - "versions"
      - "access"
      - "latest"
      - "--project=gptz-directory"
    secretEnv:
      - "NEXT_PUBLIC_FIREBASE_API_KEY"
      - "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN"
      - "NEXT_PUBLIC_FIREBASE_PROJECT_ID"
      - "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET"
      - "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID"
      - "NEXT_PUBLIC_FIREBASE_APP_ID"
      - "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID"
      - "GEMINI_API_KEY"
      - "GITHUB_TOKEN"
      - "GITHUB_OWNER"
      - "GITHUB_REPO"
      - "NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID"
      - "MAIL_HOST"
      - "MAIL_PORT"
      - "MAIL_SECURE"
      - "MAIL_USER"
      - "MAIL_PASSWORD"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID"
      - "--build-arg"
      - "GEMINI_API_KEY=$GEMINI_API_KEY"
      - "--build-arg"
      - "GITHUB_TOKEN=$GITHUB_TOKEN"
      - "--build-arg"
      - "GITHUB_OWNER=$GITHUB_OWNER"
      - "--build-arg"
      - "GITHUB_REPO=$GITHUB_REPO"
      - "--build-arg"
      - "NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID=$NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID"
      - "--build-arg"
      - "MAIL_HOST=$MAIL_HOST"
      - "--build-arg"
      - "MAIL_PORT=$MAIL_PORT"
      - "--build-arg"
      - "MAIL_SECURE=$MAIL_SECURE"
      - "--build-arg"
      - "MAIL_USER=$MAIL_USER"
      - "--build-arg"
      - "MAIL_PASSWORD=$MAIL_PASSWORD"
      - "-t"
      - "gcr.io/$PROJECT_ID/gptz-directory:$COMMIT_SHA"
      - "."

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "gptz-directory"
      - "--image"
      - "gcr.io/$PROJECT_ID/gptz-directory:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"

images:
  - "gcr.io/$PROJECT_ID/gptz-directory:$COMMIT_SHA"
