steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "Build Docker Image"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/gptz-directory:$COMMIT_SHA"
      - "."
    secretEnv:
      - "NEXT_PUBLIC_FIREBASE_API_KEY"
      - "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN"
      - "NEXT_PUBLIC_FIREBASE_PROJECT_ID"
      - "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET"
      - "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID"
      - "NEXT_PUBLIC_FIREBASE_APP_ID"
      - "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID"
      - "GEMINI_API_KEY"
      - "GITHUB_TOKEN"
      - "GITHUB_OWNER"
      - "GITHUB_REPO"
      - "NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID"
      - "MAIL_HOST"
      - "MAIL_PORT"
      - "MAIL_SECURE"
      - "MAIL_USER"
      - "MAIL_PASSWORD"
    volumes:
      - name: secrets-volume
        secret:
          secretName: gptz-directory-secrets # Replace with your Secret Manager secret name

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "gptz-directory"
      - "--image"
      - "gcr.io/$PROJECT_ID/gptz-directory:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"

images:
  - "gcr.io/$PROJECT_ID/gptz-directory:$COMMIT_SHA"

options:
  logging: "CLOUD_LOGGING_ONLY"

availableSecrets:
  secretManager:
    - versionName: "projects/$PROJECT_ID/secrets/gptz-directory-secrets/versions/latest"
      secretEnv:
        NEXT_PUBLIC_FIREBASE_API_KEY: "NEXT_PUBLIC_FIREBASE_API_KEY"
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN"
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: "NEXT_PUBLIC_FIREBASE_PROJECT_ID"
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET"
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID"
        NEXT_PUBLIC_FIREBASE_APP_ID: "NEXT_PUBLIC_FIREBASE_APP_ID"
        NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID"
        GEMINI_API_KEY: "GEMINI_API_KEY"
        GITHUB_TOKEN: "GITHUB_TOKEN"
        GITHUB_OWNER: "GITHUB_OWNER"
        GITHUB_REPO: "GITHUB_REPO"
        NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID: "NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID"
        MAIL_HOST: "MAIL_HOST"
        MAIL_PORT: "MAIL_PORT"
        MAIL_SECURE: "MAIL_SECURE"
        MAIL_USER: "MAIL_USER"
        MAIL_PASSWORD: "MAIL_PASSWORD"
