steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "Build Docker Image"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/gptz-directory:$COMMIT_SHA"
      - "."
    env:
      - "NEXT_PUBLIC_FIREBASE_API_KEY=$(cat /secrets/NEXT_PUBLIC_FIREBASE_API_KEY/latest)"
      - "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$(cat /secrets/NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN/latest)"
      - "NEXT_PUBLIC_FIREBASE_PROJECT_ID=$(cat /secrets/NEXT_PUBLIC_FIREBASE_PROJECT_ID/latest)"
      - "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$(cat /secrets/NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET/latest)"
      - "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$(cat /secrets/NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID/latest)"
      - "NEXT_PUBLIC_FIREBASE_APP_ID=$(cat /secrets/NEXT_PUBLIC_FIREBASE_APP_ID/latest)"
      - "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$(cat /secrets/NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID/latest)"
      - "GEMINI_API_KEY=$(cat /secrets/GEMINI_API_KEY/latest)"
      - "GITHUB_TOKEN=$(cat /secrets/GITHUB_TOKEN/latest)"
      - "GITHUB_OWNER=$(cat /secrets/GITHUB_OWNER/latest)"
      - "GITHUB_REPO=$(cat /secrets/GITHUB_REPO/latest)"
      - "NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID=$(cat /secrets/NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID/latest)"
      - "MAIL_HOST=$(cat /secrets/MAIL_HOST/latest)"
      - "MAIL_PORT=$(cat /secrets/MAIL_PORT/latest)"
      - "MAIL_SECURE=$(cat /secrets/MAIL_SECURE/latest)"
      - "MAIL_USER=$(cat /secrets/MAIL_USER/latest)"
      - "MAIL_PASSWORD=$(cat /secrets/MAIL_PASSWORD/latest)"

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "gptz-directory"
      - "--image"
      - "gcr.io/$PROJECT_ID/gptz-directory:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"

images:
  - "gcr.io/$PROJECT_ID/gptz-directory:$COMMIT_SHA"

options:
  logging: "CLOUD_LOGGING_ONLY"

availableSecrets:
  secretManager:
    - versionName: "projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_API_KEY/versions/latest"
      env: "NEXT_PUBLIC_FIREBASE_API_KEY"
    - versionName: "projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN/versions/latest"
      env: "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN"
    - versionName: "projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_PROJECT_ID/versions/latest"
      env: "NEXT_PUBLIC_FIREBASE_PROJECT_ID"
    - versionName: "projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET/versions/latest"
      env: "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET"
    - versionName: "projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID/versions/latest"
      env: "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID"
    - versionName: "projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_APP_ID/versions/latest"
      env: "NEXT_PUBLIC_FIREBASE_APP_ID"
    - versionName: "projects/$PROJECT_ID/secrets/NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID/versions/latest"
      env: "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID"
    - versionName: "projects/$PROJECT_ID/secrets/GEMINI_API_KEY/versions/latest"
      env: "GEMINI_API_KEY"
    - versionName: "projects/$PROJECT_ID/secrets/GITHUB_TOKEN/versions/latest"
      env: "GITHUB_TOKEN"
    - versionName: "projects/$PROJECT_ID/secrets/GITHUB_OWNER/versions/latest"
      env: "GITHUB_OWNER"
    - versionName: "projects/$PROJECT_ID/secrets/GITHUB_REPO/versions/latest"
      env: "GITHUB_REPO"
    - versionName: "projects/$PROJECT_ID/secrets/NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID/versions/latest"
      env: "NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID"
    - versionName: "projects/$PROJECT_ID/secrets/MAIL_HOST/versions/latest"
      env: "MAIL_HOST"
    - versionName: "projects/$PROJECT_ID/secrets/MAIL_PORT/versions/latest"
      env: "MAIL_PORT"
    - versionName: "projects/$PROJECT_ID/secrets/MAIL_SECURE/versions/latest"
      env: "MAIL_SECURE"
    - versionName: "projects/$PROJECT_ID/secrets/MAIL_USER/versions/latest"
      env: "MAIL_USER"
    - versionName: "projects/$PROJECT_ID/secrets/MAIL_PASSWORD/versions/latest"
      env: "MAIL_PASSWORD"
