steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "Build Docker Image"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/gptz-directory:$COMMIT_SHA"
      - "."
    env:
      - "NEXT_PUBLIC_FIREBASE_API_KEY=$(cat /secrets/NEXT_PUBLIC_FIREBASE_API_KEY/latest)"
      - "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$(cat /secrets/NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN/latest)"
      - "NEXT_PUBLIC_FIREBASE_PROJECT_ID=$(cat /secrets/NEXT_PUBLIC_FIREBASE_PROJECT_ID/latest)"
      - "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$(cat /secrets/NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET/latest)"
      - "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$(cat /secrets/NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID/latest)"
      - "NEXT_PUBLIC_FIREBASE_APP_ID=$(cat /secrets/NEXT_PUBLIC_FIREBASE_APP_ID/latest)"
      - "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$(cat /secrets/NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID/latest)"
      - "GEMINI_API_KEY=$(cat /secrets/GEMINI_API_KEY/latest)"
      - "GITHUB_TOKEN=$(cat /secrets/GITHUB_TOKEN/latest)"
      - "GITHUB_OWNER=$(cat /secrets/GITHUB_OWNER/latest)"
      - "GITHUB_REPO=$(cat /secrets/GITHUB_REPO/latest)"
      - "NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID=$(cat /secrets/NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID/latest)"
      - "MAIL_HOST=$(cat /secrets/MAIL_HOST/latest)"
      - "MAIL_PORT=$(cat /secrets/MAIL_PORT/latest)"
      - "MAIL_SECURE=$(cat /secrets/MAIL_SECURE/latest)"
      - "MAIL_USER=$(cat /secrets/MAIL_USER/latest)"
      - "MAIL_PASSWORD=$(cat /secrets/MAIL_PASSWORD/latest)"
    volumes:
      - name: secrets-volume
        secret:
          secretName: gptz-directory-secrets # Replace with your Secret Manager secret name

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "gptz-directory"
      - "--image"
      - "gcr.io/$PROJECT_ID/gptz-directory:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"

images:
  - "gcr.io/$PROJECT_ID/gptz-directory:$COMMIT_SHA"

options:
  logging: "CLOUD_LOGGING_ONLY"

availableSecrets:
  secretManager:
    - versionName: projects/gptz-directory/secrets/gptz-directory-secrets/versions/latest
      env:
        - "NEXT_PUBLIC_FIREBASE_API_KEY"
        - "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN"
        - "NEXT_PUBLIC_FIREBASE_PROJECT_ID"
        - "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET"
        - "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID"
        - "NEXT_PUBLIC_FIREBASE_APP_ID"
        - "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID"
        - "GEMINI_API_KEY"
        - "GITHUB_TOKEN"
        - "GITHUB_OWNER"
        - "GITHUB_REPO"
        - "NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID"
        - "MAIL_HOST"
        - "MAIL_PORT"
        - "MAIL_SECURE"
        - "MAIL_USER"
        - "MAIL_PASSWORD"
